---
functional:
  - Пользователь имеет возможность зарегистрироваться на Codebattle
  - При верном вводе логине и пароля пользователь должен войти в систему
  - При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  - Пользователь имеет возможность просматривать свой профиль
  - Пользователь имеет возможность видеть свою статистику
  - Пользователь имеет возможность видеть завершенные им игры в своем профиле
  - Пользователь имеет возможность перейти в "Настройки" своего профиля
  - Пользователь имеет возможность менять язык, выбрав один из 15 языков в настройках
  - Пользователь имеет возможность выбрать в настройках тип звука из 4 предложенных
  - Пользователь имеет возможность выбрать нужную громкость приложения путем "Перетаскивания бегунка" в настройках профиля
  - Пользователь может просмотреть рейтинг всех пользователей
  - Пользователь может вставить свое фото в своем профиле
  - Пользователь имеет возможность создать игру
  - Пользователь может выбрать уровень сложности при создании игры
  - Пользователь может отменить созданную им игру
  - Пользователь имеет возможность сдаться в игре
  - Пользователь имеет возможность выбрать фон в окне игры
  - Пользователь имеет возможность вести диалог в чате игры
  - Пользователь имеет возможность отправить отзыв об игре находясь в игре
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Игра не должна прерваться при обновлении страницы
  - При переводе сайта на русский язык странца входа должна быть полносью переведена на русский язык

implicit:
  - Пользователь должен иметь возможность удалить созданную им игру
  - Пользователь должен иметь возможность сдаться сопернику в игре
  - Должна быть возможность продолжить игру (если она не закончилась по причине выйгрыша соперника) после перезагрузки страницы

  


  
