---
functional:
  - Пользователь имеет возможность зарегистрироваться на Codebattle
  - Пользователь имеет возможность авторизоваться на Codebattle
  - При верном вводе логине и пароля пользователь должен войти в систему
  - При невалидном логине пользователь должен увидеть уведомление об ошибке
  - При входе в профиль зарегестрированного пользователя с неверном пароле пользователь должен увидеть уведомление об ошибке
  - Пользователь имеет возможность просматривать свой профиль
  - Пользователь имеет возможность видеть свою статистику
  - Пользователь имеет возможность видеть завершенные им игры в своем профиле
  - Пользователь имеет возможность перейти в "Настройки" своего профиля
  - Пользователь имеет возможность менять язык, выбрав один из 15 языков в настройках
  - Пользователь имеет возможность выбрать в настройках тип звука из 4 предложенных
  - Выбранный звук в настройках должен соответствовать звуку в игре
  - Пользователь имеет возможность выбрать нужную громкость приложения путем "Перетаскивания бегунка" в настройках профиля
  - Пользователь может просмотреть рейтинг всех пользователей
  - Пользователь может вставить свое фото в своем профиле
  - Пользователь имеет возможность создать игру
  - Пользователь может выбрать уровень сложности при создании игры
  - Пользователь имеет возможность выбрать фон в окне игры
  - Пользователь имеет возможность вести диалог в чате игры
  - Пользователь имеет возможность отправить отзыв об игре находясь в игре
  - Пользователь находится в режиме ожидания второго игрока после создания игры с другим пользователем
  - Созданная одним пользователем игра высвечивается как "доступная для подключения" у других пользователей
  - Пользователь имеет возможность подключиться к игре, созданной другим игроком
  - Пользователь видит просле начала игры - два редактора (слева свой, справа соперника)
  - Пользователь имеет возможность создать игру, пригласив друга
  - Пользователь имеет возможность получить приглашение на игру от друга
  - Пользователь может принять приглашение на игру от друга
  - Пользователь может отклонить приглашение на игру от друга

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров

implicit:
  - Пользователь имеет возможность сдаться в игре
  - Пользователь может отменить созданную им игру
  - Игра не должна прерваться при обновлении страницы
