---
functional:
  - Пользователь имеет возможность зарегистрироваться на Codebattle
  - При верном вводе логине и пароля пользователь должен войти в систему
  - При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  - Пользователь имеет возможность просматривать свой профиль
  - Пользователь имеет возможность видеть свою статистику
  - Пользователь имеет возможность видеть завершенные им игры
  - Пользователь имеет возможность перейти в "настройки" своего профиля
  - Пользователь имеет возможность менять язык, выбрав один из 15 языков в настройках
  - Пользователь имеет возможность выбрать в настройках тип звука из 4 предложенных
  - Пользователь имеет возможность выбрать нужную громкость приложения путем "перетаскивания бегунка" в настройках профиля
  - Пользователь может просмотреть рейтинг всех пользователей
  - Пользователь имеет возможность создать игру
  - Пользователь может выбрать уровень сложности при создании игры
  - Пользователь может выбрать тип игры при создании игры
  - Пользователь может выбрать длительность игры при создании игры
  - Пользователь имеет возможность выбрать задачу по названию при создании игры
  - Пользователь имеет возможность выбрать задачу по тегам при создании игры
  - Пользователь имеет возможность начать игру с другим пользователем
  - Пользователь имеет возможность выйти из текущей игры
  - Пользователь имеет возможность выбрть язык в игре
  - Пользователь имеет возможность выбрать фон в окне игры
  - Пользователь имеет возможность вести диалог в чате игры
  - Пользователь имеет возможность отправить отзыв об игре находясь в игре

  
non-functional:




implicit:
