---
functional:
  - Пользователь имеет возможность зарегистрироваться на Codebattle
  - Пользователь имеет возможность просматривать свой профиль
  - Пользователь имеет возможность видеть свою статистику
  - Пользователь имеет возможность видеть завершенные им игры



non-functional:




implicit:
